#!/bin/bash

set -eu

TEMP_PACKAGE="$(mktemp)"
BIN_DIR="/usr/local/bin"

# Variables
DOCKER_COMPOSE="1.29.2"
MS_TEAMS="1.4.00.26453-1"

# install core DNF plugins
dnf -y install dnf-plugins-core

# docker
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

# docker-compose
wget -qO "$BIN_DIR/docker-compose" "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE/docker-compose-$(uname -s)-$(uname -m)"

# terraform 
dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

# google chrome
yum -y install https://dl.google.com/linux/direct/google-chrome-stable_current_$(uname -m).rpm

# teams
yum -y install https://packages.microsoft.com/yumrepos/ms-teams/teams-$MS_TEAMS.$(uname -m).rpm

# update packages
dnf update

# install packages with DNF
dnf -y install \
	docker-ce docker-ce-cli containerd.io \
	terraform \
	keepassxc \
	java-latest-openjdk.$(uname -m) \
	python3-pip \
	ansible \
	vim \
	xclip \
	jq
	# unrar p7zip-full p7zip-rar

# install packages with snap
snap install lxd
snap install slack --classic
snap install code --classic
snap install google-cloud-sdk --classic
snap install thunderbird
# post install configurations
# docker
usermod -aG docker $USER

# docker-compose
chmod +x "$BIN_DIR/docker-compose"

	
